version: '3'
services:
  roisalen-backend:
    build: .
    volumes:
      - ./:/app
    ports:
      - 8080:8080
    links:
      - mongo
    environment:
      - MONGOLAB_URI=mongodb://mongo:27017/roisalen
  mongo:
    image: mongo
    command: mongod -v
    ports:
      - 27017

